import {
  Activity,
  AlarmClock,
  Aperture,
  Apple,
  Baby,
  Banknote,
  Barcode,
  Bath,
  Battery,
  BedDouble,
  Beer,
  Bell,
  Bike,
  Bird,
  Bone,
  BookOpen,
  Briefcase,
  Brush,
  Building2,
  Bus,
  CakeSlice,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  Church,
  CircleDollarSign,
  CirclePlay,
  Clapperboard,
  Clock,
  Cloud,
  Coffee,
  House,
  TrendingUp,
  Coins,
  CreditCard,
  Cross,
  Cookie,
  Flower2,
  Leaf,
  Mountain,
  ParkingCircle,
  Soup,
  Crown,
  CarTaxiFront,
  TramFront,
  TreePine,
  Waves,
  Dice5,
  Disc3,
  Dog,
  Drama,
  Droplets,
  Dumbbell,
  Factory,
  FerrisWheel,
  FileText,
  Film,
  Fish,
  Fuel,
  Gamepad2,
  Gavel,
  Gem,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Headphones,
  Heart,
  HeartPulse,
  Hotel,
  Hourglass,
  IceCream,
  Image,
  Joystick,
  KeyRound,
  Lamp,
  Landmark,
  Laptop,
  Library,
  Luggage,
  Mail,
  Map,
  Medal,
  Mic,
  Milk,
  Monitor,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  Palmtree,
  PawPrint,
  Percent,
  PersonStanding,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Plug,
  Podcast,
  Popcorn,
  Presentation,
  Printer,
  Puzzle,
  Rabbit,
  Radio,
  Receipt,
  Repeat,
  Rss,
  Salad,
  Sandwich,
  Scale,
  Scissors,
  Share2,
  Shield,
  Shirt,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Signal,
  Smartphone,
  Snowflake,
  Sofa,
  Speaker,
  Sparkles,
  Stethoscope,
  Store,
  Sun,
  Tag,
  Tent,
  Ticket,
  Timer,
  TrainFront,
  Trophy,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  Vault,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CategoryIconName } from "@/lib/types";
import { cn } from "@/lib/utils";

const MAP: Record<CategoryIconName, LucideIcon> = {
  utensils: Utensils,
  shopping: ShoppingBag,
  train: TrainFront,
  car: Car,
  home: House,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  heart: Heart,
  shield: Shield,
  graduation: GraduationCap,
  film: Film,
  sparkles: Sparkles,
  plane: Plane,
  building: Building2,
  map: Map,
  ticket: Ticket,
  umbrella: Umbrella,
  bag: ShoppingBag,
  landmark: Landmark,
  piggy: PiggyBank,
  repeat: Repeat,
  wallet: Wallet,
  gift: Gift,
  coins: Coins,
  trending: TrendingUp,
  briefcase: Briefcase,
  gamepad: Gamepad2,
  user: User,
  broom: Brush,
  tent: Tent,
  cup: Coffee,
  book: BookOpen,
  file: FileText,
  clock: Clock,
  dollar: CircleDollarSign,
  card: CreditCard,
  banknote: Banknote,
  receipt: Receipt,
  percent: Percent,
  calculator: Calculator,
  vault: Vault,
  cart: ShoppingCart,
  store: Store,
  tag: Tag,
  package: Package,
  barcode: Barcode,
  pizza: Pizza,
  icecream: IceCream,
  wine: Wine,
  beer: Beer,
  cake: CakeSlice,
  apple: Apple,
  sandwich: Sandwich,
  salad: Salad,
  sofa: Sofa,
  key: KeyRound,
  lamp: Lamp,
  hammer: Hammer,
  droplets: Droplets,
  bed: BedDouble,
  bath: Bath,
  plug: Plug,
  paw: PawPrint,
  bird: Bird,
  fish: Fish,
  cat: Cat,
  dog: Dog,
  rabbit: Rabbit,
  bone: Bone,
  baby: Baby,
  milk: Milk,
  palmtree: Palmtree,
  luggage: Luggage,
  ferris: FerrisWheel,
  sun: Sun,
  snow: Snowflake,
  moon: Moon,
  pill: Pill,
  activity: Activity,
  stethoscope: Stethoscope,
  pulse: HeartPulse,
  cross: Cross,
  bus: Bus,
  bike: Bike,
  ship: Ship,
  fuel: Fuel,
  factory: Factory,
  hotel: Hotel,
  shirt: Shirt,
  glasses: Glasses,
  watch: Watch,
  gem: Gem,
  scissors: Scissors,
  users: Users,
  handshake: Handshake,
  presentation: Presentation,
  scale: Scale,
  gavel: Gavel,
  drama: Drama,
  clapper: Clapperboard,
  popcorn: Popcorn,
  phone: Smartphone,
  laptop: Laptop,
  tv: Tv,
  headphones: Headphones,
  speaker: Speaker,
  printer: Printer,
  battery: Battery,
  tablet: Monitor,
  cpu: Laptop,
  palette: Palette,
  library: Library,
  church: Church,
  dice: Dice5,
  puzzle: Puzzle,
  joystick: Joystick,
  music: Music,
  mic: Mic,
  disc: Disc3,
  radio: Radio,
  guitar: Guitar,
  globe: Globe,
  signal: Signal,
  cloud: Cloud,
  mail: Mail,
  share: Share2,
  camera: Camera,
  image: Image,
  aperture: Aperture,
  trophy: Trophy,
  medal: Medal,
  run: PersonStanding,
  dumbbell: Dumbbell,
  calendar: Calendar,
  hourglass: Hourglass,
  timer: Timer,
  alarm: AlarmClock,
  bell: Bell,
  newspaper: Newspaper,
  podcast: Podcast,
  play: CirclePlay,
  crown: Crown,
  rss: Rss,
  leaf: Leaf,
  tree: TreePine,
  mountain: Mountain,
  flower: Flower2,
  waves: Waves,
  tram: TramFront,
  taxi: CarTaxiFront,
  parking: ParkingCircle,
  cookie: Cookie,
  soup: Soup,
};

export function CategoryIcon({
  name,
  className,
}: {
  name: CategoryIconName;
  className?: string;
}) {
  const Icon = MAP[name] ?? Wallet;
  return <Icon className={cn("size-5", className)} />;
}
