import {
  BookOpen,
  Briefcase,
  Brush,
  Building2,
  Car,
  CircleDollarSign,
  Clock,
  Coffee,
  Coins,
  FileText,
  Film,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  House,
  Landmark,
  Map,
  PiggyBank,
  Plane,
  Repeat,
  Shield,
  ShoppingBag,
  Sparkles,
  Tent,
  Ticket,
  TrainFront,
  TrendingUp,
  Umbrella,
  User,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { CategoryIconName } from "@/lib/types";
import { cn } from "@/lib/utils";

const MAP: Record<CategoryIconName, LucideIcon> = {
  utensils: Utensils,
  shopping: ShoppingBag,
  train: TrainFront,
  car: Car,
  home: House,
  wrench: Wrench,
  zap: Zap,
  wifi: Wifi,
  heart: Heart,
  shield: Shield,
  graduation: GraduationCap,
  film: Film,
  sparkles: Sparkles,
  plane: Plane,
  building: Building2,
  map: Map,
  ticket: Ticket,
  umbrella: Umbrella,
  bag: ShoppingBag,
  landmark: Landmark,
  piggy: PiggyBank,
  repeat: Repeat,
  wallet: Wallet,
  gift: Gift,
  coins: Coins,
  trending: TrendingUp,
  briefcase: Briefcase,
  gamepad: Gamepad2,
  user: User,
  broom: Brush,
  tent: Tent,
  cup: Coffee,
  book: BookOpen,
  file: FileText,
  clock: Clock,
  dollar: CircleDollarSign,
};

export function CategoryIcon({
  name,
  className,
}: {
  name: CategoryIconName;
  className?: string;
}) {
  const Icon = MAP[name] ?? Wallet;
  return <Icon className={cn("size-6", className)} strokeWidth={1.6} />;
}
