import { chromium } from "playwright";
import { mkdirSync } from "fs";
mkdirSync("/workspace/screenshots", { recursive: true });
const browser = await chromium.launch({ args: ["--no-sandbox"] });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "networkidle" });
await page.waitForTimeout(1200);
await page.getByRole("button", { name: "新增" }).last().click();
await page.waitForTimeout(500);
const labels = await page.locator(".grid.grid-cols-4 button span.w-full").allInnerTexts();
console.log("main", labels.length, labels);
await page.screenshot({ path: "/workspace/screenshots/qa-add-maincats.png" });
await page.getByRole("button", { name: "飲食" }).click({ force: true });
await page.waitForTimeout(400);
const sub = (await page.locator("body").innerText()).replace(/\s+/g, " ");
console.log("sub includes 使用此主分類?", sub.includes("使用此主分類"));
console.log("sub slice", sub.slice(sub.indexOf("子分類"), sub.indexOf("子分類") + 80));
await page.screenshot({ path: "/workspace/screenshots/qa-add-subcats.png" });
await browser.close();
