/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppBudgetRouteImport } from './routes/_app/budget'
import { Route as AppMoreRouteImport } from './routes/_app/more'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets.index'
import { Route as AppAssetsIdRouteImport } from './routes/_app/assets.$id'
import { Route as AppMoreIndexRouteImport } from './routes/_app/more.index'
import { Route as AppMorePageRouteImport } from './routes/_app/more.$page'
import { Route as AppReportsIndexRouteImport } from './routes/_app/reports.index'
import { Route as AppReportsCashflowRouteImport } from './routes/_app/reports.cashflow'
import { Route as AppReportsDashboardRouteImport } from './routes/_app/reports.dashboard'
import { Route as AppReportsHistoryRouteImport } from './routes/_app/reports.history'
import { Route as AppReportsLivingRouteImport } from './routes/_app/reports.living'
import { Route as AppReportsRetirementRouteImport } from './routes/_app/reports.retirement'
import { Route as AppReportsSpendingRouteImport } from './routes/_app/reports.spending'
import { Route as AppReportsTravelRouteImport } from './routes/_app/reports.travel'
import { Route as AppReportsTravelIndexRouteImport } from './routes/_app/reports.travel.index'
import { Route as AppReportsTravelIdRouteImport } from './routes/_app/reports.travel.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppMoreIndexRoute = AppMoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppMorePageRoute = AppMorePageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AppMoreRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsCashflowRoute = AppReportsCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsDashboardRoute = AppReportsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsHistoryRoute = AppReportsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsLivingRoute = AppReportsLivingRouteImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsRetirementRoute = AppReportsRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsSpendingRoute = AppReportsSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsTravelRoute = AppReportsTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppReportsTravelIndexRoute = AppReportsTravelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReportsTravelRoute,
} as any)
const AppReportsTravelIdRoute = AppReportsTravelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReportsTravelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/assets': typeof AppAssetsRouteWithChildren
  '/budget': typeof AppBudgetRoute
  '/more': typeof AppMoreRouteWithChildren
  '/reports': typeof AppReportsRouteWithChildren
  '/assets/$id': typeof AppAssetsIdRoute
  '/more/$page': typeof AppMorePageRoute
  '/reports/cashflow': typeof AppReportsCashflowRoute
  '/reports/dashboard': typeof AppReportsDashboardRoute
  '/reports/history': typeof AppReportsHistoryRoute
  '/reports/living': typeof AppReportsLivingRoute
  '/reports/retirement': typeof AppReportsRetirementRoute
  '/reports/spending': typeof AppReportsSpendingRoute
  '/reports/travel': typeof AppReportsTravelRouteWithChildren
  '/assets/': typeof AppAssetsIndexRoute
  '/more/': typeof AppMoreIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/reports/travel/$id': typeof AppReportsTravelIdRoute
  '/reports/travel/': typeof AppReportsTravelIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof OnboardingRoute
  '/budget': typeof AppBudgetRoute
  '/': typeof AppIndexRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/more/$page': typeof AppMorePageRoute
  '/reports/cashflow': typeof AppReportsCashflowRoute
  '/reports/dashboard': typeof AppReportsDashboardRoute
  '/reports/history': typeof AppReportsHistoryRoute
  '/reports/living': typeof AppReportsLivingRoute
  '/reports/retirement': typeof AppReportsRetirementRoute
  '/reports/spending': typeof AppReportsSpendingRoute
  '/assets': typeof AppAssetsIndexRoute
  '/more': typeof AppMoreIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/reports/travel/$id': typeof AppReportsTravelIdRoute
  '/reports/travel': typeof AppReportsTravelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/budget': typeof AppBudgetRoute
  '/_app/more': typeof AppMoreRouteWithChildren
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/assets/$id': typeof AppAssetsIdRoute
  '/_app/more/$page': typeof AppMorePageRoute
  '/_app/reports/cashflow': typeof AppReportsCashflowRoute
  '/_app/reports/dashboard': typeof AppReportsDashboardRoute
  '/_app/reports/history': typeof AppReportsHistoryRoute
  '/_app/reports/living': typeof AppReportsLivingRoute
  '/_app/reports/retirement': typeof AppReportsRetirementRoute
  '/_app/reports/spending': typeof AppReportsSpendingRoute
  '/_app/reports/travel': typeof AppReportsTravelRouteWithChildren
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/more/': typeof AppMoreIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/reports/travel/$id': typeof AppReportsTravelIdRoute
  '/_app/reports/travel/': typeof AppReportsTravelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/assets'
    | '/budget'
    | '/more'
    | '/reports'
    | '/assets/$id'
    | '/more/$page'
    | '/reports/cashflow'
    | '/reports/dashboard'
    | '/reports/history'
    | '/reports/living'
    | '/reports/retirement'
    | '/reports/spending'
    | '/reports/travel'
    | '/assets/'
    | '/more/'
    | '/reports/'
    | '/reports/travel/$id'
    | '/reports/travel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/budget'
    | '/'
    | '/assets/$id'
    | '/more/$page'
    | '/reports/cashflow'
    | '/reports/dashboard'
    | '/reports/history'
    | '/reports/living'
    | '/reports/retirement'
    | '/reports/spending'
    | '/assets'
    | '/more'
    | '/reports'
    | '/reports/travel/$id'
    | '/reports/travel'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/assets'
    | '/_app/budget'
    | '/_app/more'
    | '/_app/reports'
    | '/_app/'
    | '/_app/assets/$id'
    | '/_app/more/$page'
    | '/_app/reports/cashflow'
    | '/_app/reports/dashboard'
    | '/_app/reports/history'
    | '/_app/reports/living'
    | '/_app/reports/retirement'
    | '/_app/reports/spending'
    | '/_app/reports/travel'
    | '/_app/assets/'
    | '/_app/more/'
    | '/_app/reports/'
    | '/_app/reports/travel/$id'
    | '/_app/reports/travel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/assets/$id': {
      id: '/_app/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/more/': {
      id: '/_app/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof AppMoreIndexRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/more/$page': {
      id: '/_app/more/$page'
      path: '/$page'
      fullPath: '/more/$page'
      preLoaderRoute: typeof AppMorePageRouteImport
      parentRoute: typeof AppMoreRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/cashflow': {
      id: '/_app/reports/cashflow'
      path: '/cashflow'
      fullPath: '/reports/cashflow'
      preLoaderRoute: typeof AppReportsCashflowRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/dashboard': {
      id: '/_app/reports/dashboard'
      path: '/dashboard'
      fullPath: '/reports/dashboard'
      preLoaderRoute: typeof AppReportsDashboardRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/history': {
      id: '/_app/reports/history'
      path: '/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof AppReportsHistoryRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/living': {
      id: '/_app/reports/living'
      path: '/living'
      fullPath: '/reports/living'
      preLoaderRoute: typeof AppReportsLivingRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/retirement': {
      id: '/_app/reports/retirement'
      path: '/retirement'
      fullPath: '/reports/retirement'
      preLoaderRoute: typeof AppReportsRetirementRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/spending': {
      id: '/_app/reports/spending'
      path: '/spending'
      fullPath: '/reports/spending'
      preLoaderRoute: typeof AppReportsSpendingRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/travel': {
      id: '/_app/reports/travel'
      path: '/travel'
      fullPath: '/reports/travel'
      preLoaderRoute: typeof AppReportsTravelRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/reports/travel/': {
      id: '/_app/reports/travel/'
      path: '/'
      fullPath: '/reports/travel/'
      preLoaderRoute: typeof AppReportsTravelIndexRouteImport
      parentRoute: typeof AppReportsTravelRoute
    }
    '/_app/reports/travel/$id': {
      id: '/_app/reports/travel/$id'
      path: '/$id'
      fullPath: '/reports/travel/$id'
      preLoaderRoute: typeof AppReportsTravelIdRouteImport
      parentRoute: typeof AppReportsTravelRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsIdRoute: typeof AppAssetsIdRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsIdRoute: AppAssetsIdRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppMoreRouteChildren {
  AppMorePageRoute: typeof AppMorePageRoute
  AppMoreIndexRoute: typeof AppMoreIndexRoute
}

const AppMoreRouteChildren: AppMoreRouteChildren = {
  AppMorePageRoute: AppMorePageRoute,
  AppMoreIndexRoute: AppMoreIndexRoute,
}

const AppMoreRouteWithChildren =
  AppMoreRoute._addFileChildren(AppMoreRouteChildren)

interface AppReportsTravelRouteChildren {
  AppReportsTravelIdRoute: typeof AppReportsTravelIdRoute
  AppReportsTravelIndexRoute: typeof AppReportsTravelIndexRoute
}

const AppReportsTravelRouteChildren: AppReportsTravelRouteChildren = {
  AppReportsTravelIdRoute: AppReportsTravelIdRoute,
  AppReportsTravelIndexRoute: AppReportsTravelIndexRoute,
}

const AppReportsTravelRouteWithChildren =
  AppReportsTravelRoute._addFileChildren(AppReportsTravelRouteChildren)

interface AppReportsRouteChildren {
  AppReportsCashflowRoute: typeof AppReportsCashflowRoute
  AppReportsDashboardRoute: typeof AppReportsDashboardRoute
  AppReportsHistoryRoute: typeof AppReportsHistoryRoute
  AppReportsLivingRoute: typeof AppReportsLivingRoute
  AppReportsRetirementRoute: typeof AppReportsRetirementRoute
  AppReportsSpendingRoute: typeof AppReportsSpendingRoute
  AppReportsTravelRoute: typeof AppReportsTravelRouteWithChildren
  AppReportsIndexRoute: typeof AppReportsIndexRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsCashflowRoute: AppReportsCashflowRoute,
  AppReportsDashboardRoute: AppReportsDashboardRoute,
  AppReportsHistoryRoute: AppReportsHistoryRoute,
  AppReportsLivingRoute: AppReportsLivingRoute,
  AppReportsRetirementRoute: AppReportsRetirementRoute,
  AppReportsSpendingRoute: AppReportsSpendingRoute,
  AppReportsTravelRoute: AppReportsTravelRouteWithChildren,
  AppReportsIndexRoute: AppReportsIndexRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppBudgetRoute: typeof AppBudgetRoute
  AppMoreRoute: typeof AppMoreRouteWithChildren
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppBudgetRoute: AppBudgetRoute,
  AppMoreRoute: AppMoreRouteWithChildren,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
