/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as MoreRouteImport } from './routes/more'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MoreIndexRouteImport } from './routes/more.index'
import { Route as MoreAppearanceRouteImport } from './routes/more.appearance'
import { Route as MoreBackupRouteImport } from './routes/more.backup'
import { Route as MoreCategoriesRouteImport } from './routes/more.categories'
import { Route as MoreFxRouteImport } from './routes/more.fx'
import { Route as MoreImportRouteImport } from './routes/more.import'
import { Route as MoreOtherRouteImport } from './routes/more.other'
import { Route as MoreSecurityRouteImport } from './routes/more.security'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsCashflowRouteImport } from './routes/reports.cashflow'
import { Route as ReportsDashboardRouteImport } from './routes/reports.dashboard'
import { Route as ReportsHistoryRouteImport } from './routes/reports.history'
import { Route as ReportsLivingRouteImport } from './routes/reports.living'
import { Route as ReportsRetirementRouteImport } from './routes/reports.retirement'
import { Route as ReportsSpendingRouteImport } from './routes/reports.spending'
import { Route as ReportsTravelRouteImport } from './routes/reports.travel'
import { Route as ReportsTravelIndexRouteImport } from './routes/reports.travel.index'
import { Route as ReportsTravelIdRouteImport } from './routes/reports.travel.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreIndexRoute = MoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MoreRoute,
} as any)
const MoreAppearanceRoute = MoreAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => MoreRoute,
} as any)
const MoreBackupRoute = MoreBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => MoreRoute,
} as any)
const MoreCategoriesRoute = MoreCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MoreRoute,
} as any)
const MoreFxRoute = MoreFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => MoreRoute,
} as any)
const MoreImportRoute = MoreImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => MoreRoute,
} as any)
const MoreOtherRoute = MoreOtherRouteImport.update({
  id: '/other',
  path: '/other',
  getParentRoute: () => MoreRoute,
} as any)
const MoreSecurityRoute = MoreSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MoreRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsCashflowRoute = ReportsCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsDashboardRoute = ReportsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsHistoryRoute = ReportsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsLivingRoute = ReportsLivingRouteImport.update({
  id: '/living',
  path: '/living',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsRetirementRoute = ReportsRetirementRouteImport.update({
  id: '/retirement',
  path: '/retirement',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsSpendingRoute = ReportsSpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsTravelRoute = ReportsTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => ReportsRoute,
} as any)
const ReportsTravelIndexRoute = ReportsTravelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsTravelRoute,
} as any)
const ReportsTravelIdRoute = ReportsTravelIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsTravelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/more': typeof MoreRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/more/appearance': typeof MoreAppearanceRoute
  '/more/backup': typeof MoreBackupRoute
  '/more/categories': typeof MoreCategoriesRoute
  '/more/fx': typeof MoreFxRoute
  '/more/import': typeof MoreImportRoute
  '/more/other': typeof MoreOtherRoute
  '/more/security': typeof MoreSecurityRoute
  '/reports/cashflow': typeof ReportsCashflowRoute
  '/reports/dashboard': typeof ReportsDashboardRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/living': typeof ReportsLivingRoute
  '/reports/retirement': typeof ReportsRetirementRoute
  '/reports/spending': typeof ReportsSpendingRoute
  '/reports/travel': typeof ReportsTravelRouteWithChildren
  '/more/': typeof MoreIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/travel/$id': typeof ReportsTravelIdRoute
  '/reports/travel/': typeof ReportsTravelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/onboarding': typeof OnboardingRoute
  '/more/appearance': typeof MoreAppearanceRoute
  '/more/backup': typeof MoreBackupRoute
  '/more/categories': typeof MoreCategoriesRoute
  '/more/fx': typeof MoreFxRoute
  '/more/import': typeof MoreImportRoute
  '/more/other': typeof MoreOtherRoute
  '/more/security': typeof MoreSecurityRoute
  '/reports/cashflow': typeof ReportsCashflowRoute
  '/reports/dashboard': typeof ReportsDashboardRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/living': typeof ReportsLivingRoute
  '/reports/retirement': typeof ReportsRetirementRoute
  '/reports/spending': typeof ReportsSpendingRoute
  '/more': typeof MoreIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/travel/$id': typeof ReportsTravelIdRoute
  '/reports/travel': typeof ReportsTravelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/budget': typeof BudgetRoute
  '/more': typeof MoreRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reports': typeof ReportsRouteWithChildren
  '/more/appearance': typeof MoreAppearanceRoute
  '/more/backup': typeof MoreBackupRoute
  '/more/categories': typeof MoreCategoriesRoute
  '/more/fx': typeof MoreFxRoute
  '/more/import': typeof MoreImportRoute
  '/more/other': typeof MoreOtherRoute
  '/more/security': typeof MoreSecurityRoute
  '/reports/cashflow': typeof ReportsCashflowRoute
  '/reports/dashboard': typeof ReportsDashboardRoute
  '/reports/history': typeof ReportsHistoryRoute
  '/reports/living': typeof ReportsLivingRoute
  '/reports/retirement': typeof ReportsRetirementRoute
  '/reports/spending': typeof ReportsSpendingRoute
  '/reports/travel': typeof ReportsTravelRouteWithChildren
  '/more/': typeof MoreIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/travel/$id': typeof ReportsTravelIdRoute
  '/reports/travel/': typeof ReportsTravelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/budget'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/more/appearance'
    | '/more/backup'
    | '/more/categories'
    | '/more/fx'
    | '/more/import'
    | '/more/other'
    | '/more/security'
    | '/reports/cashflow'
    | '/reports/dashboard'
    | '/reports/history'
    | '/reports/living'
    | '/reports/retirement'
    | '/reports/spending'
    | '/reports/travel'
    | '/more/'
    | '/reports/'
    | '/reports/travel/$id'
    | '/reports/travel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/budget'
    | '/onboarding'
    | '/more/appearance'
    | '/more/backup'
    | '/more/categories'
    | '/more/fx'
    | '/more/import'
    | '/more/other'
    | '/more/security'
    | '/reports/cashflow'
    | '/reports/dashboard'
    | '/reports/history'
    | '/reports/living'
    | '/reports/retirement'
    | '/reports/spending'
    | '/more'
    | '/reports'
    | '/reports/travel/$id'
    | '/reports/travel'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/budget'
    | '/more'
    | '/onboarding'
    | '/reports'
    | '/more/appearance'
    | '/more/backup'
    | '/more/categories'
    | '/more/fx'
    | '/more/import'
    | '/more/other'
    | '/more/security'
    | '/reports/cashflow'
    | '/reports/dashboard'
    | '/reports/history'
    | '/reports/living'
    | '/reports/retirement'
    | '/reports/spending'
    | '/reports/travel'
    | '/more/'
    | '/reports/'
    | '/reports/travel/$id'
    | '/reports/travel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  BudgetRoute: typeof BudgetRoute
  MoreRoute: typeof MoreRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  ReportsRoute: typeof ReportsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more/': {
      id: '/more/'
      path: '/'
      fullPath: '/more/'
      preLoaderRoute: typeof MoreIndexRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/appearance': {
      id: '/more/appearance'
      path: '/appearance'
      fullPath: '/more/appearance'
      preLoaderRoute: typeof MoreAppearanceRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/backup': {
      id: '/more/backup'
      path: '/backup'
      fullPath: '/more/backup'
      preLoaderRoute: typeof MoreBackupRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/categories': {
      id: '/more/categories'
      path: '/categories'
      fullPath: '/more/categories'
      preLoaderRoute: typeof MoreCategoriesRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/fx': {
      id: '/more/fx'
      path: '/fx'
      fullPath: '/more/fx'
      preLoaderRoute: typeof MoreFxRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/import': {
      id: '/more/import'
      path: '/import'
      fullPath: '/more/import'
      preLoaderRoute: typeof MoreImportRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/other': {
      id: '/more/other'
      path: '/other'
      fullPath: '/more/other'
      preLoaderRoute: typeof MoreOtherRouteImport
      parentRoute: typeof MoreRoute
    }
    '/more/security': {
      id: '/more/security'
      path: '/security'
      fullPath: '/more/security'
      preLoaderRoute: typeof MoreSecurityRouteImport
      parentRoute: typeof MoreRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/cashflow': {
      id: '/reports/cashflow'
      path: '/cashflow'
      fullPath: '/reports/cashflow'
      preLoaderRoute: typeof ReportsCashflowRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/dashboard': {
      id: '/reports/dashboard'
      path: '/dashboard'
      fullPath: '/reports/dashboard'
      preLoaderRoute: typeof ReportsDashboardRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/history': {
      id: '/reports/history'
      path: '/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof ReportsHistoryRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/living': {
      id: '/reports/living'
      path: '/living'
      fullPath: '/reports/living'
      preLoaderRoute: typeof ReportsLivingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/retirement': {
      id: '/reports/retirement'
      path: '/retirement'
      fullPath: '/reports/retirement'
      preLoaderRoute: typeof ReportsRetirementRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/spending': {
      id: '/reports/spending'
      path: '/spending'
      fullPath: '/reports/spending'
      preLoaderRoute: typeof ReportsSpendingRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/travel': {
      id: '/reports/travel'
      path: '/travel'
      fullPath: '/reports/travel'
      preLoaderRoute: typeof ReportsTravelRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/reports/travel/': {
      id: '/reports/travel/'
      path: '/'
      fullPath: '/reports/travel/'
      preLoaderRoute: typeof ReportsTravelIndexRouteImport
      parentRoute: typeof ReportsTravelRoute
    }
    '/reports/travel/$id': {
      id: '/reports/travel/$id'
      path: '/$id'
      fullPath: '/reports/travel/$id'
      preLoaderRoute: typeof ReportsTravelIdRouteImport
      parentRoute: typeof ReportsTravelRoute
    }
  }
}

interface MoreRouteChildren {
  MoreAppearanceRoute: typeof MoreAppearanceRoute
  MoreBackupRoute: typeof MoreBackupRoute
  MoreCategoriesRoute: typeof MoreCategoriesRoute
  MoreFxRoute: typeof MoreFxRoute
  MoreImportRoute: typeof MoreImportRoute
  MoreOtherRoute: typeof MoreOtherRoute
  MoreSecurityRoute: typeof MoreSecurityRoute
  MoreIndexRoute: typeof MoreIndexRoute
}

const MoreRouteChildren: MoreRouteChildren = {
  MoreAppearanceRoute: MoreAppearanceRoute,
  MoreBackupRoute: MoreBackupRoute,
  MoreCategoriesRoute: MoreCategoriesRoute,
  MoreFxRoute: MoreFxRoute,
  MoreImportRoute: MoreImportRoute,
  MoreOtherRoute: MoreOtherRoute,
  MoreSecurityRoute: MoreSecurityRoute,
  MoreIndexRoute: MoreIndexRoute,
}

const MoreRouteWithChildren = MoreRoute._addFileChildren(MoreRouteChildren)

interface ReportsTravelRouteChildren {
  ReportsTravelIdRoute: typeof ReportsTravelIdRoute
  ReportsTravelIndexRoute: typeof ReportsTravelIndexRoute
}

const ReportsTravelRouteChildren: ReportsTravelRouteChildren = {
  ReportsTravelIdRoute: ReportsTravelIdRoute,
  ReportsTravelIndexRoute: ReportsTravelIndexRoute,
}

const ReportsTravelRouteWithChildren = ReportsTravelRoute._addFileChildren(
  ReportsTravelRouteChildren,
)

interface ReportsRouteChildren {
  ReportsCashflowRoute: typeof ReportsCashflowRoute
  ReportsDashboardRoute: typeof ReportsDashboardRoute
  ReportsHistoryRoute: typeof ReportsHistoryRoute
  ReportsLivingRoute: typeof ReportsLivingRoute
  ReportsRetirementRoute: typeof ReportsRetirementRoute
  ReportsSpendingRoute: typeof ReportsSpendingRoute
  ReportsTravelRoute: typeof ReportsTravelRouteWithChildren
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsCashflowRoute: ReportsCashflowRoute,
  ReportsDashboardRoute: ReportsDashboardRoute,
  ReportsHistoryRoute: ReportsHistoryRoute,
  ReportsLivingRoute: ReportsLivingRoute,
  ReportsRetirementRoute: ReportsRetirementRoute,
  ReportsSpendingRoute: ReportsSpendingRoute,
  ReportsTravelRoute: ReportsTravelRouteWithChildren,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  BudgetRoute: BudgetRoute,
  MoreRoute: MoreRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  ReportsRoute: ReportsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
